//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeReport.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entry
    {
        public long Id { get; set; }
        public System.DateTime From { get; set; }
        public System.DateTime To { get; set; }
        public int UserId { get; set; }
        public int TypeId { get; set; }
        public string Comment { get; set; }
    
        public virtual EntryType EntryType { get; set; }
        public virtual User User { get; set; }
    }
}
